CREATE DATABASE QLKhachHang;
USE QLKhachHang;


CREATE TABLE KhachHang (
    TenDN NVARCHAR(50) PRIMARY KEY,
    MatKhau NVARCHAR(50),
    HoTen NVARCHAR(100),
    NgaySinh DATE,
    GioiTinh BIT,
    Email NVARCHAR(100),
    ThuNhap FLOAT
);

ALTER TABLE KhachHang
ADD CONSTRAINT PK_TenDN PRIMARY KEY (TenDN);

-- Ràng bu?c NOT NULL
ALTER TABLE KhachHang
ALTER COLUMN MatKhau NVARCHAR(50) NOT NULL;

ALTER TABLE KhachHang
ALTER COLUMN HoTen NVARCHAR(100) NOT NULL;

ALTER TABLE KhachHang
ALTER COLUMN NgaySinh DATE NOT NULL;

ALTER TABLE KhachHang
ALTER COLUMN Email NVARCHAR(100) NOT NULL;

ALTER TABLE KhachHang
ALTER COLUMN ThuNhap FLOAT NOT NULL;

-- Ràng bu?c CHECK
ALTER TABLE KhachHang
ADD CONSTRAINT CHK_GioiTinh CHECK (GioiTinh IN (0, 1));

-- Ràng bu?c UNIQUE
ALTER TABLE KhachHang
ADD CONSTRAINT UQ_Email UNIQUE (Email);

-- Ràng bu?c DEFAULT
ALTER TABLE KhachHang
ADD CONSTRAINT DF_NgaySinh DEFAULT GETDATE() FOR NgaySinh;

ALTER TABLE KhachHang
ADD CONSTRAINT chk_Email CHECK (Email LIKE '%_@__%.__%');

ALTER TABLE KhachHang
ADD CONSTRAINT chk_ThuNhap CHECK (ThuNhap BETWEEN 1000000 AND 50000000);